routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Laravel\Jetstream\Http\Controllers\Livewire\UserProfileController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/health', function () {
    config()->set('session.driver', 'array');
    return response('Healthy', 200)
        ->header('Content-Type', 'text/plain');
});

Route::middleware(['portal'])->get('/welcome', function () {
    return view('portal.welcome');
})->name('welcome');

Route::middleware(['portal', 'auth:trainee'])->get('/help', function () {
    return view('portal.help-dashboard');
})->name('help');

Route::middleware(['portal', 'auth:trainee'])->get('/', function () {
    return view('portal.index');
})->name('portal');

Route::group(['middleware' => config('jetstream.middleware', ['web'])], function () {
    Route::group(['middleware' => ['auth:web', 'verified']], function () {

        Route::prefix('admin')->group(function() {

            Route::get('/dashboard', function () {
                return view('dashboard');
            })->name('dashboard');

            // User & Profile...
            Route::get('/user/profile', [UserProfileController::class, 'show'])
                ->name('profile.show');
        });
    });
});

app/Models/Message.php
<?php


namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Message extends Model
{

}

app/Models/Trainee.php
<?php


namespace App\Models;

use Grosv\LaravelPasswordlessLogin\Traits\PasswordlessLogin;
use Illuminate\Foundation\Auth\User as Authenticatable;

class Trainee extends Authenticatable
{
    use PasswordlessLogin;

    protected $guard = 'trainee';

    protected $hidden = [
        'password',
    ];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Fortify\TwoFactorAuthenticatable;
use Laravel\Jetstream\HasProfilePhoto;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens;
    use HasFactory;
    use HasProfilePhoto;
    use Notifiable;
    use TwoFactorAuthenticatable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
        'two_factor_recovery_codes',
        'two_factor_secret',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = [
        'profile_photo_url',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Livewire/Audios.php
<?php


namespace App\Http\Livewire;

use App\Models\Message;
use Livewire\Component;

class Audios extends Component
{
    public function render()
    {
        return view('portal.audios', [
            'messages' => Message::query()->whereActive(1)->get()
        ]);
    }
}

app/Http/Livewire/HelpDashboard.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class HelpDashboard extends Component
{
    public function render()
    {
        return view('layout.help-dashboard');
    }
}

app/Http/Livewire/LanguageDropdown.php
<?php


namespace App\Http\Livewire;

use Livewire\Component;

class LanguageDropdown extends Component
{
    use LivewireLocaleTrait;

    public function setLocale(string $local)
    {
        app()->setLocale($local);
        session()->put('locale', $local);

        return redirect()->to('/');
    }

    public function render()
    {
        return view('portal.language');
    }
}

app/Http/Livewire/LivewireLocaleTrait.php
<?php

namespace App\Http\Livewire;


trait LivewireLocaleTrait
{
    public $livewireLocale;

    public $livewireLocales;

    public function mount()
    {
        $this->livewireLocale = app()->getLocale();
        $this->livewireLocales = config('app.locales');
    }
}

app/Http/Livewire/TraineeDetail.php
<?php

namespace App\Http\Livewire;

use Illuminate\Support\Facades\Auth;
use Livewire\Component;

class TraineeDetail extends Component
{
    public function render()
    {
        return view('portal.trainee-detail', [
            'trainee' => Auth::user()
        ]);
    }
}

app/Http/Livewire/Trainees.php
<?php


namespace App\Http\Livewire;

use App\Models\Trainee;
use Livewire\Component;

class Trainees extends Component
{
    public function render()
    {
        return view('admin.trainees', [
            'trainees' => Trainee::query()->get()
        ]);
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/admin/trainees.blade.php
<table id="usersTable" class="stripe hover" style="width:100%; padding-top: 1em;  padding-bottom: 1em;">
    <thead>
    <tr>
        <th data-priority="1">First Name</th>
        <th data-priority="1">Last Name</th>
        <th data-priority="2">Group</th>
        <th data-priority="2">Language</th>
    </tr>
    </thead>
    <tbody>
    @foreach($trainees as $key => $trainee)
        <tr>
            <td>{{ $trainee->first_name }}</td>
            <td>{{ $trainee->last_name }}</td>
            <td>{{ $trainee->group }}</td>
            <td>{{ $trainee->language }}</td>
        </tr>
    @endforeach
    </tbody>

</table>

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            Trainee List
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                <div class="p-6 sm:px-20 bg-white border-b border-gray-200">
                    @livewire('trainees')
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Nunito:400,600,700" rel="stylesheet">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">

        <!-- Scripts -->
        <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.2.1/dist/alpine.js" defer></script>
    </head>
    <body>
        <div class="font-sans text-gray-900 antialiased">
            {{ $slot }}
        </div>
    </body>
</html>

resources/views/portal/audios.blade.php
@if (count($messages) > 0)
    <div class="row">
        <div class="col-md-12">
            <div class="card card-chart">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-6 ml-auto mr-auto text-center">
                            <h5 class="card-title">{{ __('training.training_audio') }}</h5>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="row">
                        @foreach($messages as $key => $message)
                            <div class="ml-1">
                            </div>
                            <div class="ml-3">
                                <h6>{{ __('training.message') . ' ' . ($key + 1) }}</h6>
                                <audio controls>
                                    <source src="{{$message->path}}" type="audio/mpeg">
                                    Your browser does not support the audio tag.
                                </audio>
                            </div>
                            <div class="ml-1">
                            </div>
                        @endforeach
                    </div>
                </div>
                <div class="card-footer">
                </div>
            </div>
        </div>
    </div>
@endif

resources/views/portal/help-dashboard.blade.php
<!--
=========================================================
* Paper Dashboard 2 - v2.0.1
=========================================================

* Product Page: https://www.creative-tim.com/product/paper-dashboard-2
* Copyright 2020 Creative Tim (https://www.creative-tim.com)

Coded by www.creative-tim.com

 =========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
-->
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="{{ asset('img/apple-icon.png') }}">
    <link rel="icon" type="image/png" href="{{ asset('img/favicon.png') }}">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>
        {{ __('training.title') }}
    </title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
    <link href="{{ asset('css/app.css') }}" rel="stylesheet" />
    <link href="{{ asset('css/style.css') }}" rel="stylesheet" />

    @livewireStyles

    <style>
        video {
            display: block;
            width: auto;
            margin: 0 auto;
        }
    </style>
</head>

<body class="">
<div class="wrapper ">
    <div class="sidebar" data-color="white" data-active-color="danger">
        <div class="logo">
            <a href="/" class="simple-text logo-mini">
                <div class="logo-image-small">
                    <img src="{{ asset('img/default-avatar.png') }}">
                </div>
            </a>
            <a href="/" class="simple-text logo-normal">
                {{ Auth::user()->first_name }}
            </a>
        </div>
        <div class="sidebar-wrapper">
            <ul class="nav">
                <li>
                    <a href="/">
                        <i class="nc-icon nc-bank"></i>
                        <p>{{ __('training.home') }}</p>
                    </a>
                </li>
                <li class="active ">
                    <a href="/help" >
                        <i class="nc-icon nc-alert-circle-i"></i>
                        <p>{{ __('training.help') }}</p>
                    </a>
                </li>
                <li class="active-pro">
                </li>
            </ul>
        </div>
    </div>
    <div class="main-panel">
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-absolute fixed-top navbar-transparent">
            <div class="container-fluid">
                <div class="navbar-wrapper">
                    <div class="navbar-toggle">
                        <button type="button" class="navbar-toggler">
                            <span class="navbar-toggler-bar bar1"></span>
                            <span class="navbar-toggler-bar bar2"></span>
                            <span class="navbar-toggler-bar bar3"></span>
                        </button>
                    </div>
                    <a class="navbar-brand" href="javascript:;">{{ __('training.meeting_online') }}</a>
                </div>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-bar navbar-kebab"></span>
                    <span class="navbar-toggler-bar navbar-kebab"></span>
                    <span class="navbar-toggler-bar navbar-kebab"></span>
                </button>

                @livewire('language-dropdown')

            </div>
        </nav>
        <!-- End Navbar -->
        <div class="content">
            <div class="row">
                <div class="col-md-8">
                    <div class="card card-chart">
                        <div class="card-header">
                            <div class="row">
                                <div class="col-md-12 ml-auto mr-auto text-center">
                                    <h5 class="card-title"> {{ __('training.help_video') }} </h5>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <h6></h6>
                                    <video height="240" controls>
                                        <source src="{{ asset('videos/help_'.app()->getLocale().'.mp4') }}" type="video/mp4">
                                        Your browser does not support the video tag.
                                    </video>
                                </div>
                                <div class="col-md-6">
                                    <h6></h6>
                                    <video height="240" controls>
                                        <source src="{{ asset('videos/help_'.app()->getLocale().'_c.mp4') }}" type="video/mp4">
                                        Your browser does not support the video tag.
                                    </video>
                                </div>
                            </div>
                            <div class="row">
                            </div>
                        </div>
                        <div class="card-footer ">
                            <hr>
                        </div>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="card ">
                        <div class="card-header ">
                            <div class="row">
                                <div class="col-md-6 ml-auto mr-auto text-center">
                                    <h5 class="card-title">{{ __('training.contact_helpdesk') }}</h5>
                                </div>
                            </div>
                        </div>
                        <div class="card-body ">
                            <div class="row">
                                <div class="update ml-auto mr-auto">
                                    <a target="_blank" href="https://tinyurl.com/HelpVT2020" class="btn btn-success btn-round">{{ __('training.join_whatsapp') }}</a>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer ">
                            <hr>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <footer class="footer footer-black  footer-white ">
            <div class="container-fluid">
                <div class="row">
                </div>
            </div>
        </footer>
    </div>

</div>

@livewireScripts
<!--   Core JS Files   -->
<script src="{{ asset('js/core/jquery.min.js') }}"></script>
<script src="{{ asset('js/core/popper.min.js') }}"></script>
<script src="{{ asset('js/core/bootstrap.min.js') }}"></script>
<script src="{{ asset('js/plugins/perfect-scrollbar.jquery.min.js') }}"></script>
<!-- Chart JS -->
<script src="{{ asset('js/plugins/chartjs.min.js') }}"></script>
<!--  Notifications Plugin    -->
<script src="{{ asset('js/plugins/bootstrap-notify.js') }}"></script>
<!-- Control Center for Now Ui Dashboard: parallax effects, scripts for the example pages etc -->
<script src="{{ asset('js/app.js') }}" type="text/javascript"></script>

</body>

</html>

resources/views/portal/index.blade.php
<!--
=========================================================
* Paper Dashboard 2 - v2.0.1
=========================================================

* Product Page: https://www.creative-tim.com/product/paper-dashboard-2
* Copyright 2020 Creative Tim (https://www.creative-tim.com)

Coded by www.creative-tim.com

 =========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
-->
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="{{ asset('img/apple-icon.png') }}">
    <link rel="icon" type="image/png" href="{{ asset('img/favicon.png') }}">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>
        {{ __('training.title') }}
    </title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
    <link href="{{ asset('css/app.css') }}" rel="stylesheet" />
    <link href="{{ asset('css/style.css') }}" rel="stylesheet" />

    @livewireStyles
</head>

<body class="">
<div class="wrapper ">
    <div class="sidebar" data-color="white" data-active-color="danger">
        <div class="logo">
            <a href="/" class="simple-text logo-mini">
                <div class="logo-image-small">
                    <img src="{{ asset('img/default-avatar.png') }}">
                </div>
            </a>
            <a href="/" class="simple-text logo-normal">
                {{ Auth::user()->first_name }}
            </a>
        </div>
        <div class="sidebar-wrapper">
            <ul class="nav">
                <li class="active ">
                    <a href="/">
                        <i class="nc-icon nc-bank"></i>
                        <p>{{ __('training.home') }}</p>
                    </a>
                </li>
                <li>
                    <a href="/help" >
                        <i class="nc-icon nc-alert-circle-i"></i>
                        <p>{{ __('training.help') }}</p>
                    </a>
                </li>
                <li class="active-pro">
                </li>
            </ul>
        </div>
    </div>
    <div class="main-panel">
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-absolute fixed-top navbar-transparent">
            <div class="container-fluid">
                <div class="navbar-wrapper">
                    <div class="navbar-toggle">
                        <button type="button" class="navbar-toggler">
                            <span class="navbar-toggler-bar bar1"></span>
                            <span class="navbar-toggler-bar bar2"></span>
                            <span class="navbar-toggler-bar bar3"></span>
                        </button>
                    </div>
                    <a class="navbar-brand" href="javascript:;">{{ __('training.meeting_online') }}</a>
                </div>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-bar navbar-kebab"></span>
                    <span class="navbar-toggler-bar navbar-kebab"></span>
                    <span class="navbar-toggler-bar navbar-kebab"></span>
                </button>

                @livewire('language-dropdown')

            </div>
        </nav>
        <!-- End Navbar -->
        <div class="content">
            <div class="row">
                <div class="col-md-8">
                    <div class="card card-chart">
                        <div class="card-header">
                            <div class="row">
                                <div class="col-md-12 ml-auto mr-auto text-center">
                                    <h5 class="card-title"> {{ __('training.itero') }} </h5>
                                </div>
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-6 ml-auto mr-auto text-center">
                                    <h6>{{ __('training.october') }} 2020</h6>
                                </div>
                            </div>
                            <div class="row">
                                @livewire('trainee-detail')
                            </div>

                        </div>
                        <div class="card-footer ">
                            <hr>
                            <div class="stats"><i class="fa fa-info"></i> {{ __('training.click_on_buttons') }} </div>
                        </div>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="card ">
                        <div class="card-header ">
                            <div class="row">
                                <div class="col-md-6 ml-auto mr-auto text-center">
                                    <h5 class="card-title">{{ __('training.meetings') }}</h5>
                                </div>
                            </div>
                        </div>
                        <div class="card-body ">
                            <div class="row">
                                <div class="update ml-auto mr-auto">
                                    <a target="_blank" href="https://us02web.zoom.us/j/85009484307" class="btn btn-success btn-round">{{ __('training.join_meetings') }}</a>
                                </div>
                            </div>

                            <div class="row">
                                <div class="update ml-auto mr-auto">
                                    <a class="btn btn-warning btn-round" href="/help">{{ __('training.helpdesk') }}</a>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer ">
                            <hr>
                            <div class="stats">
                                <i class="fa fa-calendar"></i>{{ __('training.no_of_trainees') }}: {{ App\Models\Trainee::count() }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            @livewire('audios')

            <div class="row">
                <div class="col-md-8">
                    <div class="card card-chart">
                        <div class="card-header">
                            <div class="row">
                                <div class="col-md-12 ml-auto mr-auto text-center">
                                    <h5 class="card-title">{{ __('training.outlines') }} & {{ __('training.schedule') }}</h5>
                                </div>
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-6 ml-auto mr-auto text-center">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6 ml-auto mr-auto text-center">
                                    <a href="{{ asset('documents/outline_'.app()->getLocale().'.pdf') }}" target="_blank" class="btn btn-default btn-round"> {{ __('training.outlines') }} </a>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6 ml-auto mr-auto text-center">
                                    <a target="_blank" href="{{ asset('documents/schedule_'.app()->getLocale().'.pdf') }}" class="btn btn-default btn-round"> {{ __('training.schedule') }} </a>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer ">
                            <hr>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <footer class="footer footer-black  footer-white ">
            <div class="container-fluid">
                <div class="row">
                </div>
            </div>
        </footer>
    </div>

</div>

@livewireScripts
<!--   Core JS Files   -->
<script src="{{ asset('js/core/jquery.min.js') }}"></script>
<script src="{{ asset('js/core/popper.min.js') }}"></script>
<script src="{{ asset('js/core/bootstrap.min.js') }}"></script>
<script src="{{ asset('js/plugins/perfect-scrollbar.jquery.min.js') }}"></script>
<!-- Chart JS -->
<script src="{{ asset('js/plugins/chartjs.min.js') }}"></script>
<!--  Notifications Plugin    -->
<script src="{{ asset('js/plugins/bootstrap-notify.js') }}"></script>
<!-- Control Center for Now Ui Dashboard: parallax effects, scripts for the example pages etc -->
<script src="{{ asset('js/app.js') }}" type="text/javascript"></script>

</body>

</html>

resources/views/portal/language.blade.php
<div class="collapse navbar-collapse justify-content-end" id="navigation">

    <ul class="navbar-nav">

        <li class="nav-item btn-rotate dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="nc-icon nc-world-2"></i>
                <p>
                    @lang('training.'.$livewireLocale)
                </p>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                @foreach($livewireLocales as $locale)
                    <a class="dropdown-item" wire:click.prevent="setLocale('{{$locale}}')" role="button" href="#">@lang('training.'.$locale)</a>
                @endforeach
            </div>
        </li>
    </ul>
</div>

resources/views/portal/trainee-detail.blade.php
<div class="card-body ">
    <div class="row">
        <div class="col-md-5">
            <div class="form-group">
                <label>{{ __('training.username') }}</label>
                <input type="text" class="form-control" disabled=""  value="{{ $trainee->user_name }}">
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label>{{ __('training.name') }}</label>
                <input type="text" class="form-control" disabled="" value="{{ $trainee->first_name }} {{ $trainee->last_name }}">
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <label>{{ __('training.group') }}</label>
                <input type="text" class="form-control" disabled=""  value="{{ $trainee->group }}">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-5">
            <div class="form-group">
                <label for="exampleInputEmail1">{{ __('training.email') }}</label>
                <input type="text" disabled="" class="form-control" value="{{ $trainee->email }}">
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label>{{ __('training.language') }}</label>
                <input type="text" class="form-control" disabled="" value="{{ $trainee->language }}">
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <label>{{ __('training.city') }}</label>
                <input type="text" class="form-control" disabled="" value="-">
            </div>
        </div>
    </div>
</div>